import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Level 3 of the game 
 * 
 * @author Michael Ma, Ricky Chen
 * @version 1 
 */
public class Level3 extends Controller
{
    private EnemiesIcon enemyIcon ; 
    /**
     * Constructor for objects of class Level3.
     * 
     */
    public Level3()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(24, 16, 40); 
    }

    public Level3(Player player,InvisiblePlayer invisPlayer,Arrow arrow, EnemiesIcon enemyIcon)
    {
        super(24,16,40);
        level = 3;
        bgm = new GreenfootSound("Level3.mp3");
        prepare();
        addObject(player,2,13);
        addObject(invisPlayer,2,13);
        addObject(arrow,2,14);
        addObject(enemyIcon,0,0) ; 
        DisplayText text = new DisplayText(player);
        addObject(text,2,0);
    }

    /**
     * Prepare the world for the start of the program. That is: create the initial
     * objects and add them to the world.
     */
    /**
     * Prepare the world for the start of the program. That is: create the initial
     * objects and add them to the world.
     */
    private void prepare()
    {
        bgm.playLoop();
        BloodyWoodenFloor bloodywoodenfloor = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor, 0, 15);
        BloodyWoodenFloor bloodywoodenfloor2 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor2, 0, 14);
        BloodyWoodenFloor bloodywoodenfloor3 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor3, 0, 13);
        BloodyWoodenFloor bloodywoodenfloor4 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor4, 0, 12);
        BloodyWoodenFloor bloodywoodenfloor5 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor5, 0, 11);
        BloodyWoodenFloor bloodywoodenfloor6 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor6, 0, 10);
        BloodyWoodenFloor bloodywoodenfloor7 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor7, 0, 9);
        BloodyWoodenFloor bloodywoodenfloor8 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor8, 0, 8);
        BloodyWoodenFloor bloodywoodenfloor9 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor9, 0, 7);
        BloodyWoodenFloor bloodywoodenfloor10 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor10, 0, 6);
        BloodyWoodenFloor bloodywoodenfloor11 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor11, 0, 4);
        BloodyWoodenFloor bloodywoodenfloor12 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor12, 0, 5);
        BloodyWoodenFloor bloodywoodenfloor13 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor13, 0, 3);
        BloodyWoodenFloor bloodywoodenfloor14 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor14, 0, 2);
        BloodyWoodenFloor bloodywoodenfloor15 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor15, 0, 1);
        BloodyWoodenFloor bloodywoodenfloor16 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor16, 1, 0);
        BloodyWoodenFloor bloodywoodenfloor17 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor17, 0, 0);
        BloodyWoodenFloor bloodywoodenfloor18 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor18, 2, 0);
        BloodyWoodenFloor bloodywoodenfloor19 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor19, 3, 0);
        BloodyWoodenFloor bloodywoodenfloor20 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor20, 4, 0);
        BloodyWoodenFloor bloodywoodenfloor21 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor21, 5, 0);
        BloodyWoodenFloor bloodywoodenfloor22 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor22, 6, 0);
        BloodyWoodenFloor bloodywoodenfloor23 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor23, 7, 0);
        BloodyWoodenFloor bloodywoodenfloor24 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor24, 9, 0);
        BloodyWoodenFloor bloodywoodenfloor25 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor25, 8, 0);
        BloodyWoodenFloor bloodywoodenfloor26 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor26, 13, 0);
        BloodyWoodenFloor bloodywoodenfloor27 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor27, 12, 0);
        BloodyWoodenFloor bloodywoodenfloor28 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor28, 11, 0);
        BloodyWoodenFloor bloodywoodenfloor29 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor29, 10, 0);
        BloodyWoodenFloor bloodywoodenfloor30 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor30, 15, 0);
        BloodyWoodenFloor bloodywoodenfloor31 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor31, 14, 0);
        BloodyWoodenFloor bloodywoodenfloor32 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor32, 17, 0);
        BloodyWoodenFloor bloodywoodenfloor33 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor33, 16, 0);
        BloodyWoodenFloor bloodywoodenfloor34 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor34, 19, 0);
        BloodyWoodenFloor bloodywoodenfloor35 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor35, 18, 0);
        BloodyWoodenFloor bloodywoodenfloor36 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor36, 22, 0);
        BloodyWoodenFloor bloodywoodenfloor37 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor37, 21, 0);
        BloodyWoodenFloor bloodywoodenfloor38 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor38, 20, 0);
        BloodyWoodenFloor bloodywoodenfloor39 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor39, 23, 0);
        BloodyWoodenFloor bloodywoodenfloor40 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor40, 23, 1);
        BloodyWoodenFloor bloodywoodenfloor41 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor41, 23, 2);
        BloodyWoodenFloor bloodywoodenfloor42 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor42, 23, 3);
        BloodyWoodenFloor bloodywoodenfloor43 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor43, 23, 4);
        BloodyWoodenFloor bloodywoodenfloor44 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor44, 23, 5);
        BloodyWoodenFloor bloodywoodenfloor45 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor45, 23, 6);
        BloodyWoodenFloor bloodywoodenfloor46 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor46, 23, 7);
        BloodyWoodenFloor bloodywoodenfloor47 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor47, 23, 8);
        BloodyWoodenFloor bloodywoodenfloor48 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor48, 23, 10);
        BloodyWoodenFloor bloodywoodenfloor49 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor49, 23, 9);
        BloodyWoodenFloor bloodywoodenfloor50 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor50, 23, 11);
        BloodyWoodenFloor bloodywoodenfloor51 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor51, 23, 12);
        BloodyWoodenFloor bloodywoodenfloor52 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor52, 23, 14);
        BloodyWoodenFloor bloodywoodenfloor53 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor53, 23, 13);
        BloodyWoodenFloor bloodywoodenfloor54 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor54, 23, 15);
        BloodyWoodenFloor bloodywoodenfloor55 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor55, 22, 15);
        BloodyWoodenFloor bloodywoodenfloor56 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor56, 21, 15);
        BloodyWoodenFloor bloodywoodenfloor57 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor57, 20, 15);
        BloodyWoodenFloor bloodywoodenfloor58 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor58, 19, 15);
        BloodyWoodenFloor bloodywoodenfloor59 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor59, 18, 15);
        BloodyWoodenFloor bloodywoodenfloor60 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor60, 16, 15);
        BloodyWoodenFloor bloodywoodenfloor61 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor61, 17, 15);
        BloodyWoodenFloor bloodywoodenfloor62 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor62, 15, 15);
        BloodyWoodenFloor bloodywoodenfloor63 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor63, 14, 15);
        BloodyWoodenFloor bloodywoodenfloor64 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor64, 13, 15);
        BloodyWoodenFloor bloodywoodenfloor65 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor65, 12, 15);
        BloodyWoodenFloor bloodywoodenfloor66 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor66, 11, 15);
        BloodyWoodenFloor bloodywoodenfloor67 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor67, 10, 15);
        BloodyWoodenFloor bloodywoodenfloor68 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor68, 9, 15);
        BloodyWoodenFloor bloodywoodenfloor69 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor69, 8, 15);
        BloodyWoodenFloor bloodywoodenfloor70 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor70, 7, 15);
        BloodyWoodenFloor bloodywoodenfloor71 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor71, 6, 15);
        BloodyWoodenFloor bloodywoodenfloor72 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor72, 5, 15);
        BloodyWoodenFloor bloodywoodenfloor73 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor73, 4, 15);
        BloodyWoodenFloor bloodywoodenfloor74 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor74, 3, 15);
        BloodyWoodenFloor bloodywoodenfloor75 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor75, 2, 15);
        BloodyWoodenFloor bloodywoodenfloor76 = new BloodyWoodenFloor();
        addObject(bloodywoodenfloor76, 1, 15);
        WoodenWall woodenwall = new WoodenWall();
        addObject(woodenwall, 1, 14);
        WoodenWall woodenwall2 = new WoodenWall();
        addObject(woodenwall2, 2, 14);
        WoodenWall woodenwall3 = new WoodenWall();
        addObject(woodenwall3, 3, 14);
        WoodenWall woodenwall4 = new WoodenWall();
        addObject(woodenwall4, 4, 14);
        WoodenWall woodenwall5 = new WoodenWall();
        addObject(woodenwall5, 4, 13);
        WoodenWall woodenwall6 = new WoodenWall();
        addObject(woodenwall6, 4, 12);
        WoodenWall woodenwall7 = new WoodenWall();
        addObject(woodenwall7, 4, 10);
        WoodenWall woodenwall8 = new WoodenWall();
        addObject(woodenwall8, 3, 10);
        WoodenWall woodenwall9 = new WoodenWall();
        addObject(woodenwall9, 2, 10);
        woodenwall8.setLocation(1, 10);
        WoodenWall woodenwall10 = new WoodenWall();
        addObject(woodenwall10, 5, 10);
        WoodenWall woodenwall11 = new WoodenWall();
        addObject(woodenwall11, 6, 10);
        WoodenWall woodenwall12 = new WoodenWall();
        addObject(woodenwall12, 6, 12);
        WoodenWall woodenwall13 = new WoodenWall();
        addObject(woodenwall13, 6, 13);
        WoodenWall woodenwall14 = new WoodenWall();
        addObject(woodenwall14, 7, 13);
        WoodenWall woodenwall15 = new WoodenWall();
        addObject(woodenwall15, 8, 13);
        WoodenWall woodenwall16 = new WoodenWall();
        addObject(woodenwall16, 9, 13);
        WoodenWall woodenwall17 = new WoodenWall();
        addObject(woodenwall17, 10, 13);
        WoodenWall woodenwall18 = new WoodenWall();
        addObject(woodenwall18, 10, 12);
        WoodenWall woodenwall19 = new WoodenWall();
        addObject(woodenwall19, 10, 10);
        WoodenWall woodenwall20 = new WoodenWall();
        addObject(woodenwall20, 9, 10);
        WoodenWall woodenwall21 = new WoodenWall();
        addObject(woodenwall21, 8, 10);
        WoodenWall woodenwall22 = new WoodenWall();
        addObject(woodenwall22, 7, 10);
        WoodenWall woodenwall23 = new WoodenWall();
        addObject(woodenwall23, 8, 9);
        WoodenWall woodenwall24 = new WoodenWall();
        addObject(woodenwall24, 8, 8);
        WoodenWall woodenwall25 = new WoodenWall();
        addObject(woodenwall25, 7, 8);
        WoodenWall woodenwall26 = new WoodenWall();
        addObject(woodenwall26, 6, 8);
        WoodenWall woodenwall27 = new WoodenWall();
        addObject(woodenwall27, 5, 8);
        WoodenWall woodenwall28 = new WoodenWall();
        addObject(woodenwall28, 4, 8);
        WoodenWall woodenwall29 = new WoodenWall();
        addObject(woodenwall29, 4, 6);
        WoodenWall woodenwall30 = new WoodenWall();
        addObject(woodenwall30, 4, 7);
        WoodenWall woodenwall31 = new WoodenWall();
        addObject(woodenwall31, 2, 6);
        WoodenWall woodenwall32 = new WoodenWall();
        addObject(woodenwall32, 1, 6);
        WoodenWall woodenwall33 = new WoodenWall();
        addObject(woodenwall33, 1, 5);
        WoodenWall woodenwall34 = new WoodenWall();
        addObject(woodenwall34, 1, 4);
        WoodenWall woodenwall35 = new WoodenWall();
        addObject(woodenwall35, 1, 3);
        WoodenWall woodenwall36 = new WoodenWall();
        addObject(woodenwall36, 1, 2);
        WoodenWall woodenwall37 = new WoodenWall();
        addObject(woodenwall37, 1, 1);
        WoodenWall woodenwall38 = new WoodenWall();
        addObject(woodenwall38, 2, 1);
        WoodenWall woodenwall39 = new WoodenWall();
        addObject(woodenwall39, 3, 1);
        WoodenWall woodenwall40 = new WoodenWall();
        addObject(woodenwall40, 4, 1);
        WoodenWall woodenwall41 = new WoodenWall();
        addObject(woodenwall41, 5, 1);
        WoodenWall woodenwall42 = new WoodenWall();
        addObject(woodenwall42, 4, 4);
        WoodenWall woodenwall43 = new WoodenWall();
        addObject(woodenwall43, 3, 4);
        WoodenWall woodenwall44 = new WoodenWall();
        addObject(woodenwall44, 4, 3);
        WoodenWall woodenwall45 = new WoodenWall();
        addObject(woodenwall45, 4, 2);
        WoodenWall woodenwall46 = new WoodenWall();
        addObject(woodenwall46, 6, 7);
        WoodenWall woodenwall47 = new WoodenWall();
        addObject(woodenwall47, 6, 6);
        WoodenWall woodenwall48 = new WoodenWall();
        addObject(woodenwall48, 6, 5);
        WoodenWall woodenwall49 = new WoodenWall();
        addObject(woodenwall49, 6, 4);
        WoodenWall woodenwall50 = new WoodenWall();
        addObject(woodenwall50, 7, 4);
        WoodenWall woodenwall51 = new WoodenWall();
        addObject(woodenwall51, 8, 4);
        WoodenWall woodenwall52 = new WoodenWall();
        addObject(woodenwall52, 8, 3);
        WoodenWall woodenwall53 = new WoodenWall();
        addObject(woodenwall53, 8, 2);
        WoodenWall woodenwall54 = new WoodenWall();
        addObject(woodenwall54, 8, 1);
        WoodenWall woodenwall55 = new WoodenWall();
        addObject(woodenwall55, 7, 1);
        WoodenWall woodenwall56 = new WoodenWall();
        addObject(woodenwall56, 6, 1);
        WoodenWall woodenwall57 = new WoodenWall();
        addObject(woodenwall57, 9, 4);
        woodenwall56.setLocation(10, 4);
        WoodenWall woodenwall58 = new WoodenWall();
        addObject(woodenwall58, 11, 4);
        WoodenWall woodenwall59 = new WoodenWall();
        addObject(woodenwall59, 12, 4);
        WoodenWall woodenwall60 = new WoodenWall();
        addObject(woodenwall60, 12, 14);
        WoodenWall woodenwall61 = new WoodenWall();
        addObject(woodenwall61, 12, 13);
        WoodenWall woodenwall62 = new WoodenWall();
        addObject(woodenwall62, 13, 14);
        WoodenWall woodenwall63 = new WoodenWall();
        addObject(woodenwall63, 14, 14);
        WoodenWall woodenwall64 = new WoodenWall();
        addObject(woodenwall64, 14, 12);
        WoodenWall woodenwall65 = new WoodenWall();
        addObject(woodenwall65, 14, 11);
        WoodenWall woodenwall66 = new WoodenWall();
        addObject(woodenwall66, 14, 10);
        WoodenWall woodenwall67 = new WoodenWall();
        addObject(woodenwall67, 13, 10);
        WoodenWall woodenwall68 = new WoodenWall();
        addObject(woodenwall68, 12, 10);
        WoodenWall woodenwall69 = new WoodenWall();
        addObject(woodenwall69, 14, 9);
        WoodenWall woodenwall70 = new WoodenWall();
        addObject(woodenwall70, 14, 8);
        WoodenWall woodenwall71 = new WoodenWall();
        addObject(woodenwall71, 14, 7);
        WoodenWall woodenwall72 = new WoodenWall();
        addObject(woodenwall72, 14, 5);
        WoodenWall woodenwall73 = new WoodenWall();
        addObject(woodenwall73, 14, 4);
        WoodenWall woodenwall74 = new WoodenWall();
        addObject(woodenwall74, 14, 6);
        WoodenWall woodenwall75 = new WoodenWall();
        addObject(woodenwall75, 12, 5);
        WoodenWall woodenwall76 = new WoodenWall();
        addObject(woodenwall76, 12, 6);
        WoodenWall woodenwall77 = new WoodenWall();
        addObject(woodenwall77, 12, 7);
        WoodenWall woodenwall78 = new WoodenWall();
        addObject(woodenwall78, 12, 8);
        WoodenWall woodenwall79 = new WoodenWall();
        addObject(woodenwall79, 11, 8);
        WoodenWall woodenwall80 = new WoodenWall();
        addObject(woodenwall80, 10, 8);
        WoodenWall woodenwall81 = new WoodenWall();
        addObject(woodenwall81, 13, 1);
        WoodenWall woodenwall82 = new WoodenWall();
        addObject(woodenwall82, 13, 2);
        WoodenWall woodenwall83 = new WoodenWall();
        addObject(woodenwall83, 14, 2);
        WoodenWall woodenwall84 = new WoodenWall();
        addObject(woodenwall84, 14, 3);
        WoodenWall woodenwall85 = new WoodenWall();
        addObject(woodenwall85, 16, 1);
        WoodenWall woodenwall86 = new WoodenWall();
        addObject(woodenwall86, 16, 2);
        WoodenWall woodenwall87 = new WoodenWall();
        addObject(woodenwall87, 16, 3);
        WoodenWall woodenwall88 = new WoodenWall();
        addObject(woodenwall88, 16, 4);
        WoodenWall woodenwall89 = new WoodenWall();
        addObject(woodenwall89, 16, 5);
        WoodenWall woodenwall90 = new WoodenWall();
        addObject(woodenwall90, 16, 6);
        WoodenWall woodenwall91 = new WoodenWall();
        addObject(woodenwall91, 16, 7);
        WoodenWall woodenwall92 = new WoodenWall();
        addObject(woodenwall92, 16, 8);
        woodenwall91.setLocation(17, 8);
        WoodenWall woodenwall93 = new WoodenWall();
        addObject(woodenwall93, 18, 8);
        WoodenWall woodenwall94 = new WoodenWall();
        addObject(woodenwall94, 21, 8);
        WoodenWall woodenwall95 = new WoodenWall();
        addObject(woodenwall95, 20, 8);
        WoodenWall woodenwall96 = new WoodenWall();
        addObject(woodenwall96, 19, 8);
        WoodenWall woodenwall97 = new WoodenWall();
        addObject(woodenwall97, 21, 7);
        WoodenWall woodenwall98 = new WoodenWall();
        addObject(woodenwall98, 21, 6);
        WoodenWall woodenwall99 = new WoodenWall();
        addObject(woodenwall99, 20, 6);
        WoodenWall woodenwall100 = new WoodenWall();
        addObject(woodenwall100, 19, 6);
        WoodenWall woodenwall101 = new WoodenWall();
        addObject(woodenwall101, 18, 6);
        WoodenWall woodenwall102 = new WoodenWall();
        addObject(woodenwall102, 17, 6);
        WoodenWall woodenwall103 = new WoodenWall();
        addObject(woodenwall103, 18, 3);
        WoodenWall woodenwall104 = new WoodenWall();
        addObject(woodenwall104, 18, 4);
        WoodenWall woodenwall105 = new WoodenWall();
        addObject(woodenwall105, 18, 5);
        WoodenWall woodenwall106 = new WoodenWall();
        addObject(woodenwall106, 18, 1);
        WoodenWall woodenwall107 = new WoodenWall();
        addObject(woodenwall107, 19, 1);
        WoodenWall woodenwall108 = new WoodenWall();
        addObject(woodenwall108, 20, 1);
        WoodenWall woodenwall109 = new WoodenWall();
        addObject(woodenwall109, 22, 1);
        WoodenWall woodenwall110 = new WoodenWall();
        addObject(woodenwall110, 22, 2);
        WoodenWall woodenwall111 = new WoodenWall();
        addObject(woodenwall111, 22, 3);
        WoodenWall woodenwall112 = new WoodenWall();
        addObject(woodenwall112, 22, 4);
        WoodenWall woodenwall113 = new WoodenWall();
        addObject(woodenwall113, 22, 5);
        woodenwall98.setLocation(22, 6);
        woodenwall97.setLocation(22, 7);
        woodenwall94.setLocation(22, 8);
        WoodenWall woodenwall114 = new WoodenWall();
        addObject(woodenwall114, 20, 7);
        WoodenWall woodenwall115 = new WoodenWall();
        addObject(woodenwall115, 22, 9);
        WoodenWall woodenwall116 = new WoodenWall();
        addObject(woodenwall116, 22, 10);
        WoodenWall woodenwall117 = new WoodenWall();
        addObject(woodenwall117, 22, 11);
        WoodenWall woodenwall118 = new WoodenWall();
        addObject(woodenwall118, 22, 12);
        WoodenWall woodenwall119 = new WoodenWall();
        addObject(woodenwall119, 22, 13);
        WoodenWall woodenwall120 = new WoodenWall();
        addObject(woodenwall120, 22, 14);
        WoodenWall woodenwall121 = new WoodenWall();
        addObject(woodenwall121, 20, 14);
        WoodenWall woodenwall122 = new WoodenWall();
        addObject(woodenwall122, 21, 14);
        WoodenWall woodenwall123 = new WoodenWall();
        addObject(woodenwall123, 19, 14);
        WoodenWall woodenwall124 = new WoodenWall();
        addObject(woodenwall124, 15, 14);
        WoodenWall woodenwall125 = new WoodenWall();
        addObject(woodenwall125, 16, 14);
        WoodenWall woodenwall126 = new WoodenWall();
        addObject(woodenwall126, 17, 14);
        WoodenWall woodenwall127 = new WoodenWall();
        addObject(woodenwall127, 18, 14);
        WoodenWall woodenwall128 = new WoodenWall();
        addObject(woodenwall128, 15, 8);
        WoodenWall woodenwall129 = new WoodenWall();
        addObject(woodenwall129, 16, 10);
        WoodenWall woodenwall130 = new WoodenWall();
        addObject(woodenwall130, 17, 10);
        WoodenWall woodenwall131 = new WoodenWall();
        addObject(woodenwall131, 18, 10);
        WoodenWall woodenwall132 = new WoodenWall();
        addObject(woodenwall132, 18, 11);
        WoodenWall woodenwall133 = new WoodenWall();
        addObject(woodenwall133, 18, 13);
        WoodenWall woodenwall134 = new WoodenWall();
        addObject(woodenwall134, 20, 10);
        WoodenWall woodenwall135 = new WoodenWall();
        addObject(woodenwall135, 21, 10);
        WoodenDoor woodendoor = new WoodenDoor();
        addObject(woodendoor, 2, 4);
        WoodenDoor woodendoor2 = new WoodenDoor();
        addObject(woodendoor2, 3, 6);
        WoodenDoor woodendoor3 = new WoodenDoor();
        addObject(woodendoor3, 4, 9);
        WoodenDoor woodendoor4 = new WoodenDoor();
        addObject(woodendoor4, 6, 11);
        WoodenDoor woodendoor5 = new WoodenDoor();
        addObject(woodendoor5, 10, 11);
        WoodenDoor woodendoor6 = new WoodenDoor();
        addObject(woodendoor6, 14, 13);
        WoodenDoor woodendoor7 = new WoodenDoor();
        addObject(woodendoor7, 19, 10);
        IronDoor irondoor = new IronDoor();
        addObject(irondoor, 3, 10);
        IronDoor irondoor2 = new IronDoor();
        addObject(irondoor2, 4, 11);
        IronDoor irondoor3 = new IronDoor();
        addObject(irondoor3, 18, 2);
        ButtonTiles buttontiles = new ButtonTiles(-2, -1);
        addObject(buttontiles, 7, 9);
        ButtonTiles buttontiles2 = new ButtonTiles(0, 0);
        addObject(buttontiles2, 5, 1);
        ButtonTiles buttontiles3 = new ButtonTiles(-1, 0);
        addObject(buttontiles3, 5, 1);
        ButtonTiles buttontiles4 = new ButtonTiles(-1, 0);
        addObject(buttontiles4, 4, 1);
        ButtonTiles buttontiles5 = new ButtonTiles(1, 1);
        addObject(buttontiles5, 13, 10);
        ButtonTiles buttontiles6 = new ButtonTiles(0, -1);
        addObject(buttontiles6, 19, 7);
        ButtonTiles buttontiles7 = new ButtonTiles(0, 12);
        addObject(buttontiles7, 14, 1);
        PotionSpawner potionspawner = new PotionSpawner();
        addObject(potionspawner, 1, 8);
        PotionSpawner potionspawner2 = new PotionSpawner();
        addObject(potionspawner2, 6, 9);
        PotionSpawner potionspawner3 = new PotionSpawner();
        addObject(potionspawner3, 8, 11);
        PotionSpawner potionspawner4 = new PotionSpawner();
        addObject(potionspawner4, 17, 3);
        PotionSpawner potionspawner5 = new PotionSpawner();
        addObject(potionspawner5, 17, 4);
        PotionSpawner potionspawner6 = new PotionSpawner();
        addObject(potionspawner6, 17, 5);
        PotionSpawner potionspawner7 = new PotionSpawner();
        addObject(potionspawner7, 20, 11);
        PotionSpawner potionspawner8 = new PotionSpawner();
        addObject(potionspawner8, 20, 13);
        BronzeKey bronzekey = new BronzeKey();
        addObject(bronzekey, 1, 7);
        BronzeKey bronzekey2 = new BronzeKey();
        addObject(bronzekey2, 2, 11);
        BronzeKey bronzekey3 = new BronzeKey();
        addObject(bronzekey3, 7, 12);
        AllPotion allpotion = new AllPotion();
        addObject(allpotion, 9, 12);
        RedSlime redslime = new RedSlime(3);
        addObject(redslime, 3, 9);
        RedSlime redslime2 = new RedSlime(3);
        addObject(redslime2, 3, 5);
        RedSlime redslime3 = new RedSlime(3);
        addObject(redslime3, 6, 14);
        CorruptSamurai corruptsamurai = new CorruptSamurai(3);
        addObject(corruptsamurai, 10, 14);
        TrapTiles traptiles = new TrapTiles();
        addObject(traptiles, 8, 14);
        CorruptSamurai corruptsamurai2 = new CorruptSamurai(3);
        addObject(corruptsamurai2, 16, 12);
        Plant plant = new Plant();
        addObject(plant, 18, 12);
        Plant plant2 = new Plant();
        addObject(plant2, 15, 10);
        Hole hole = new Hole();
        addObject(hole, 21, 1);
        TroubledAlice troubledalice = new TroubledAlice();
        addObject(troubledalice, 6, 1);
        PickyRicky pickyricky = new PickyRicky();
        addObject(pickyricky, 11, 1);
        CorruptSamurai corruptsamurai3 = new CorruptSamurai(3);
        addObject(corruptsamurai3, 10, 1);
        GoldKey key = new GoldKey();
        addObject(key,9,5);
        GoldenChest chest = new GoldenChest();
        addObject(chest,7,5);
        Golem golem = new Golem(level);
        addObject(golem, 9, 6);
        WiseJeff wisejeff = new WiseJeff();
        addObject(wisejeff, 9, 8);
        Slime slime = new Slime(3);
        addObject(slime, 3, 2);
        Slime slime2 = new Slime(3);
        addObject(slime2, 2, 2);
        Slime slime3 = new Slime(3);
        addObject(slime3, 3, 3);
        Slime slime4 = new Slime(3);
        addObject(slime4, 2, 3);
        SilverKey silverkey = new SilverKey() ; 
        addObject(silverkey, 3, 11) ;
        TrapTiles traptiles2 = new TrapTiles() ; 
        addObject(traptiles2, 15, 5) ; 
    }
}
